routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();



Route::group(['middleware' => 'auth'], function () {
    // Authentication Routes...
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/category','CategoryController');
    Route::resource('/sub_category','SubCategoryController');
    Route::resource('/customer','CustomerController');
    Route::post('customer-list', 'CustomerController@customer_list');
    Route::get('get_customer', 'CustomerController@get_customer');
    //Users
    Route::post('user-list', 'UserController@user_list');
    Route::resource('users', 'UserController');
    Route::resource('categories', 'CategoryController');
    Route::resource('brands', 'BrandController');
    //Attributes
    Route::resource('attributes', 'AttributeController');
    //Get Attribute Group By Id
    Route::post('fetch-attribute-group/{any}', 'AttributeController@fetch_attribute_group');
    //Delete Attribute  By Id
    Route::delete('delete-attribute/{any}', 'AttributeController@delete_attribute');
    //update Attribute By Id
    Route::post('attributes-update/{any}', 'AttributeController@attributes_update');

    Route::resource('products', 'ProductController');
    Route::post('products/upload', 'ProductController@upload')->name('products.upload');
    Route::get('get-products', 'ProductController@get_products');
    Route::get('get-product-by-id', 'ProductController@get_product_by_id');
     //Upload Summernote Image
    Route::post('summurnote-image-upload', 'AttributeController@summurnote_image_upload');
    Route::resource('units', 'UnitController');
    Route::resource('pos','PosController');
    //Role & Permission
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
//Purchase start
Route::resource('purchase','PurchaseController');
Route::get('get-purchase', 'PurchaseController@get_purchase');
Route::get('get-supplier', 'PurchaseController@get_supplier');
 Route::get('get-supplier-by-id', 'PurchaseController@get_supplier_by_id');
//Route::post('store', 'PurchaseController@store');
    //purchase end

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';
    
    public function attributes() {
        return $this->belongsToMany(Attribute::class, 'products_attributes');
    }
    
    public function categories() {
        return $this->belongsToMany(Category::class, 'products_categories');
    }
    
    public function product_images() {
        return $this->hasMany(Image::class);
    }
    
    public function product_main_category() {
        return $this->belongsTo(Category::class, 'main_category');
    }
    
    public function brand() {
        return $this->belongsTo(Brand::class);
    }
    
    public function scopeFindByCategorySlug($query, $categorySlug) {
        return $query->whereHas('product_main_category', function ($query) use ($categorySlug) {
                    $query->where('slug', $categorySlug);
                });
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Product;
use App\Models\Brand;
use App\Models\Unit;
use App\Models\AttributeGroup;
use Auth;
use DB;

class ProductController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $data['all_product'] = Product::all();
        // echo '<pre>';print_r($data['all_product']);
        return view('product.all_product', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $all_category = Category::all();
        $data['all_brand'] = Brand::all();
        $data['all_unit'] = Unit::all();

        $data['all_attribute_with_group'] = AttributeGroup::with('attributes')->get();
        

        $category = array(
            'categories' => array(),
            'parent_cats' => array()
        );

        foreach ($all_category as $row) {
            $category['categories'][$row->id] = $row;
            $category['parent_cats'][$row->parent_id][] = $row->id;
        }
        
//        echo '<pre>';print_r($data['all_attribute_with_group']);die;
        $category_list = "<ul class=''><li class='form-control-label text-right main-category'>Main category</li>" . $this->buildCategory('', $category) . "</ul>";

        $data['category_list'] = $category_list;
        return view('product.add_product', $data);
    }

    /**
     * Build Category List
     *
     * @param  parent_id and $category[]
     * @return Category List
     */
    public function buildCategory($parent, $category, $database_cat = '') {
        $html = "";
        if (isset($category['parent_cats'][$parent])) {
            $html .= "<ul class=''>";
//            $html .= "<li class='form-control-label text-right main-category'>Main category</li>";
            foreach ($category['parent_cats'][$parent] as $cat_id) {
//                echo '<pre>';print_r($category['categories'][$cat_id]['id']);
                if (!isset($category['parent_cats'][$cat_id])) {
                    $html .= "<li> "
                            . " <label>" .
                            '<input type="checkbox" name="category[]" value="' . $category['categories'][$cat_id]['id'] . '"> ' . $category['categories'][$cat_id]->category_name .
                            '<input type="radio" class="default-category" name="main_category" value="' . $category['categories'][$cat_id]['id'] . '"> ' . '' .
                            "</label>"
                            . "</li>";
                }
                if (isset($category['parent_cats'][$cat_id])) {
                    $html .= "<li> <label>" .
                            '<input type="checkbox" name="category[]" value="' . $category['categories'][$cat_id]['id'] . '"> ' . $category['categories'][$cat_id]->category_name .
                            '<input type="radio" class="default-category" name="main_category" value="' . $category['categories'][$cat_id]['id'] . '"> ' . '' .
                            "</label>";
                    $html .= $this->buildCategory($cat_id, $category);
                    $html .= "</li>";
                }
            }
            $html .= "</ul>";
        }
        return $html;
    }

    /**
     * Upload a newly created file in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return File Path
     */
    public function upload(Request $request) {

//        echo '<pre>';print_r($request->file('file'));die;
        $upload_folder = 'products';

        $path = $request->file('file')->storeAs($upload_folder, $request->file('file')->getClientOriginalName());

        return $path;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $product = new Product;

        $request->validate([
            'name' => 'required|unique:products',
            'brand' => 'required',
            'main_category' => 'required',
            'price' => 'required',
            'quantity' => 'required',
            'unit' => 'required',
            'sku' => 'required|unique:products',
        ]);
        
        $response['status'] = 'Error';

        $product->name = $request->name;
        $product->brand_id = $request->brand;
//        $product->vendor_id = $request->vendor;
        $product->main_category = $request->main_category;
        $product->slug = $request->slug;
        $product->sku = $request->sku;
        $product->ean = $request->ean;
        $product->tags = $request->tags;
        $product->price = $request->price;
        $product->quantity = $request->quantity;
        $product->unit = $request->unit;
        $product->short_description = $request->short_description;
        $product->description = $request->description;
        $product->tags = $request->tags;
        $product->created_by = Auth::user()->id;
        $product->meta_title = $request->meta_title;
        $product->meta_description = $request->meta_description;
        $product->meta_keywords = $request->meta_keywords;
        $product->status = '0';
        if($request->status) {
            $product->status = $request->status;
        }
        
        $product->save();
        
        $data_category = array();
        if($request->category) {
            foreach ($request->category as $value) {           
                $data_category['product_id'] = $product->id;
                $data_category['category_id'] = $value;
                //$product->categories()->attach($data_category);
                DB::table('products_categories')->insert($data_category);
            }
        }
        
        $data_attribute = array();
        if($request->attribute) {
            foreach ($request->attribute as $row) {           
//                $data_attribute['product_id'] = $product->id;
//                $data_attribute['attribute_id'] = $row;
//                $data_attribute['product_attribute_quantity'] = $request->quantity;
                
                $data_attribute[] = [
                    'product_id' => $product->id,
                    'attribute_id' => $row,
                    'product_attribute_quantity' => $request->quantity
                ];
                //$product->attributes()->attach($data_attribute);
            }
            DB::table('products_attributes')->insert($data_attribute);
        }
        
        $data_image = array();
        $i = 0;
        if($request->images_name) {
            foreach ($request->images_name as $row) {           
                $data_image['product_id'] = $product->id;
                $data_image['images_name'] = $row;
                $data_image['is_main_image'] = 0;
                if($i == 0) {
                    $data_image['is_main_image'] = 1;
                }

                //$product->attributes()->attach($data_attribute);
                DB::table('products_images')->insert($data_image);
            }
        }
        
        if(isset($product->id)) {
            $response['status'] = 'Success';
        }
        
        echo json_encode($response);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $data['product_data'] = Product::find($id);
        $all_category = Category::all();
        $data['all_brand'] = Brand::all();
        
        $data['all_attribute_with_group'] = AttributeGroup::with('attributes')->get();

        $category = array(
            'categories' => array(),
            'parent_cats' => array()
        );

        foreach ($all_category as $row) {
            $category['categories'][$row->id] = $row;
            $category['parent_cats'][$row->parent_id][] = $row->id;
        }
        
        $product_attibute_array = array();
        foreach ($data['product_data']->attributes as $row) {
            $product_attibute_array[] = $row->pivot->attribute_id;
        }


//        echo '<pre>';print_r($data['product_data']->attributes()->with("attribute_group")->get());die;
        $data['product_attibute_array'] = $product_attibute_array;
        $category_list = "<ul class=''><li class='form-control-label text-left main-category'>Main category</li>" . $this->buildCategory('', $category, $data['product_data']->main_category) . "</ul>";
        $data['category_list'] = $category_list;
        
        return view('product.edit_product', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $product = Product::find($id);

        $request->validate([
            'name' => 'required|unique:products,name,'. $id,
            'brand' => 'required',
            'main_category' => 'required',
            'price' => 'required',
            'quantity' => 'required',
            'sku' => 'required|unique:products,sku,'. $id,
        ]);
        
        $response['status'] = 'Error';

        $product->name = $request->name;
        $product->brand_id = $request->brand;
        $product->main_category = $request->main_category;
        $product->slug = $request->slug;
        $product->sku = $request->sku;
        $product->ean = $request->ean;
        $product->tags = $request->tags;
        $product->price = $request->price;

resources/views/product/all_product.blade.php
@extends('layouts.master')

@section('content')
<div class="col-12 pt-5">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">All Products</h4>
            
            @if(Auth::user()->can('add-product'))
            <div class="card-tools">
                <a href="{{url('products/create')}}" class="btn btn-info btn-md">
                    <i class="fa fa-plus-circle"></i>Add New Product
                </a>
            </div>
            @endif
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Sl</th>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Category</th>
                        <th>Brand</th>
                        <th>Price</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($all_product as $row)
                    <tr>
                        <td>
                            {{ $loop->iteration }}
                        </td>
                        <td>
                            <img src="{{ asset("storage/app/".$row->product_images[0]->images_name) }}" alt="brand image" style="width: 80px;">
                        </td>
                        <td>
                            {{ $row->name }}
                        </td>
                        <td>
                            {{ $row->product_main_category->category_name }}
                        </td>
                        <td>
                            {{ $row->brand->brand_name }}
                        </td>
                        <td>
                            {{ $row->price }}
                        </td>
                        <td>
                            @if($row->status == '1')
                            Active
                            @else
                            Inactive
                            @endif
                        </td>
                        <td>

                            <a href=""  class="btn btn-primary btn-sm mr-2 float-left">
                                View
                            </a> 
                                                      
                            @if(Auth::user()->can('edit-product'))
                            <a href="products/{{ $row->id }}/edit"  class="btn btn-success btn-sm mr-2 float-left text-white">
                                Edit
                            </a> 
                            @endif
                            

                            @if(Auth::user()->can('delete-product'))
                            <form method="post" action="{{ route('products.destroy', $row->id) }}" style="display: inline-block;">
                                @csrf
                                @method('DELETE')
                                <button onclick="return confirm('Are you sure want to delete this?');" type="submit" class="btn btn-danger btn-sm float-left">Delete</button>
                            </form>
                            @endif
                        </td>
                    </tr>
                    @endforeach
                        
                </tbody>
            </table>
        </div>
    </div>
    
    
</div>


@endsection